### ISSUE TITLE
include fwd/rwd and speed buttons

### ISSUE THREAD

**Issue by ghost** [vyleung/logseq-helium-plugin#10]
hi! 
would it be possible to add rewind and forward buttons? so when i play a video and i want to go back 10 seconds to listen to the same passage, i'd click the rewind button. also, setting the playback speed could be interesting!

thanks!

**Comment by vyleung** [comment]
hello! skipping forward and backward (rewinding) are already available for youtube and local videos. 

as for adjusting the playback speed, i can work on adding this feature though it'd probably be limited to youtube and local videos

**Comment by ghost** [comment]
i should have read the instructions! nevertheless, rwd and fwd works for me using the keyboard combination (ctrl+alt+L/K), but it doesn't work for me using my mouse. i'm on windows 10, i will try it on osx too.

whenever you get to adding the playback speed feature, i'd appreciate it.

thanks!

**Comment by vyleung** [comment]
[v.2.1.0](https://github.com/vyleung/logseq-helium-plugin/releases/tag/v.2.1.0) should fix the issue you mentioned and add the playback speed feature - let me know if these things work for you 🙂

**Comment by ghost** [comment]
looks and works beautifully!
