### ISSUE TITLE
Hi！ Can it be used with obsidian?

### ISSUE THREAD

**Issue by hou0** [vyleung/logseq-helium-plugin#19]
Hi！ Can it be used with obsidian?

**Comment by vyleung** [comment]
hi, apologies for the late response - this plugin doesn't work with obsidian. similar plugins for obsidian include [juliang22/ObsidianTimestampNotes](https://github.com/juliang22/ObsidianTimestampNotes) and [aidenlx/media-extended](https://github.com/aidenlx/media-extended)
