### ISSUE TITLE
Make keyboard shortcut optional

### ISSUE THREAD

**Issue by sethyuan** [vyleung/logseq-helium-plugin#2]
Hi, first of all, I want to say that this is a very useful plugin for video note taking!

But, I don't want to use a keybinding in this case so, can you make it optional?

**Comment by vyleung** [comment]
hi Seth, glad you find the plugin useful! i find your tocgen plugin super useful, so thanks for creating it 🙂 this is a good suggestion - inserting "NA" in the keyboard shortcut setting will now make it optional in [v.1.1.1](https://github.com/vyleung/logseq-helium-plugin/releases/tag/v.1.1.1)
