### ISSUE TITLE
Feature request: Enlarge or narrow with Proportion.

### ISSUE THREAD

**Issue by mzwlevi** [vyleung/logseq-helium-plugin#4]
The  helium-plugin is wonderful, which solve the problem with write video notes in logseq 🎉.
Any plan to add the function: Enlarge or narrow with Proportion?
This will improve efficiency, currently I need to increase the height then increase the width 🥲.

**Comment by vyleung** [comment]
thanks for the feature request! a new option has been added in [v.1.1.3](https://github.com/vyleung/logseq-helium-plugin/releases/tag/v.1.1.3) to simultaneously increase/decrease the height and width of youtube videos - let me know if this works for you

![logseq_helium_issue4_update](https://user-images.githubusercontent.com/64292157/168449352-85e80b56-a361-4354-baf2-5e4f8e77b158.png)

**Comment by mzwlevi** [comment]
> thanks for the feature request! a new option has been added in [v.1.1.3](https://github.com/vyleung/logseq-helium-plugin/releases/tag/v.1.1.3) to simultaneously increase/decrease the height and width of youtube videos - let me know if this works for you
> 
> ![logseq_helium_issue4_update](https://user-images.githubusercontent.com/64292157/168449352-85e80b56-a361-4354-baf2-5e4f8e77b158.png)

nice!

**Comment by mzwlevi** [comment]
> thanks for the feature request! a new option has been added in [v.1.1.3](https://github.com/vyleung/logseq-helium-plugin/releases/tag/v.1.1.3) to simultaneously increase/decrease the height and width of youtube videos - let me know if this works for you
> 
> ![logseq_helium_issue4_update](https://user-images.githubusercontent.com/64292157/168449352-85e80b56-a361-4354-baf2-5e4f8e77b158.png)

I have updated the latest helium version, but it does not work for me, I'm using the v0.6.8 of Logseq.
<img width="373" alt="Screen Shot 2022-05-15 at 09 41 05" src="https://user-images.githubusercontent.com/78029539/168453720-cf1722e4-da68-4349-9b7b-ca8d041b18a6.png">

https://user-images.githubusercontent.com/78029539/168453723-a6101eae-5920-46ad-b736-f5d4c78a1102.mov

**Comment by mzwlevi** [comment]
I have cleared the cache, reindex, reopen LS, reinstall helium, back to the default theme, but nothing happened.

**Comment by vyleung** [comment]
that's super weird - i tried to reproduce this error but couldn't

https://user-images.githubusercontent.com/64292157/168454274-bb8de065-08b1-4e5d-b91b-0774f1c364f1.mp4

can you disable and re-enable the plugin? then open dev tools (mac: `cmd+option+i` | windows: `ctrl+shift+i`) - you should see "logseq-helium-plugin loaded". let me know if there are any errors that pop up

**Comment by mzwlevi** [comment]
When I click the start float, the console shows:
<img width="1337" alt="Screen Shot 2022-05-15 at 10 15 44" src="https://user-images.githubusercontent.com/78029539/168454357-7f9054a4-b1c1-4745-a5eb-476b235db393.png">

**Comment by vyleung** [comment]
can you go into edit mode for the block w/ the video and send a screenshot? it may be an issue w/ the format of the url

**Comment by mzwlevi** [comment]
![Screen Shot 2022-05-15 at 10 22 26](https://user-images.githubusercontent.com/78029539/168454475-5d862cc5-05ae-4f98-ab18-9e4053758f37.png)

**Comment by mzwlevi** [comment]
![Screen Shot 2022-05-15 at 10 24 32](https://user-images.githubusercontent.com/78029539/168454524-6cc9aea6-cb04-4ea1-9adc-442769450585.png)
I found this in the console

**Comment by vyleung** [comment]
gotcha - the plugin doesn't currently support the shortened url format. i'll work on adding this to the next release

can you try using the video's full url? - `{{youtube https://www.youtube.com/watch?v=JbBUlojyvhs}}`

**Comment by mzwlevi** [comment]
> gotcha - the plugin doesn't currently support the shortened url format. i'll work on adding this to the next release
> 
> can you try using the video's full url? - `{{youtube https://www.youtube.com/watch?v=JbBUlojyvhs}}`

Nice, It works, thank you!  👍

**Comment by vyleung** [comment]
happy to hear that!

**Comment by vyleung** [comment]
shortened YouTube URLs should now be supported in [v.1.1.4](https://github.com/vyleung/logseq-helium-plugin/releases/tag/v.1.1.4)

**Comment by mzwlevi** [comment]
> shortened YouTube URLs should now be supported in [v.1.1.4](https://github.com/vyleung/logseq-helium-plugin/releases/tag/v.1.1.4)

👏
