### ISSUE TITLE
Problems when floating the video

### ISSUE THREAD

**Issue by mendax1234** [vyleung/logseq-helium-plugin#6]
My logseq version is 0.6.9 , it seems that after select the whole part of code of the video. l choose the `start floating` , but nothing happens. Can you give some more specific steps on how to float the video. Thanks!

My operating system is windows10 pro.

**Comment by vyleung** [comment]
hi Daniel! floating the video should be as simple as what you’ve described. what type of video are you trying to float (e.g. YouTube, Vimeo, local video)? 

if you’re able to, could you screen record a quick video of the issue?

**Comment by mendax1234** [comment]
It seems that l don't know how to `start floating`. l find that after l click the red ballon , what should l do? When should l select my code?

**Comment by vyleung** [comment]
hopefully [this video](https://www.loom.com/share/48d156a741064b96b885e058cf580df9) helps to clarify

**Comment by mendax1234** [comment]
Thanks , that'r great , l can float the video now!

**Comment by mendax1234** [comment]
@vyleung Do you know how to change the size of window of the video?

**Comment by vyleung** [comment]
check out [this video](https://www.loom.com/share/7f01b6240f7c4452bd9e5da5d3dd0ff1) starting at the 10 sec mark

**Comment by mendax1234** [comment]
Thanks , but it seems that l only have this red ballon . l don't have the button to change the size.
![image](https://user-images.githubusercontent.com/62934294/169733600-b721f609-aa3f-420f-81cc-23737a689251.png)

**Comment by vyleung** [comment]
i forgot to mention - currently, only YouTube videos can be resized

**Comment by mendax1234** [comment]
Oh, thanks.

**Comment by mendax1234** [comment]
Can you add the local video support? Thanks!

**Comment by mendax1234** [comment]
Besides , with the youtube video, l still can't change the size.
![image](https://user-images.githubusercontent.com/62934294/169734705-5129f72d-8233-4d5c-91f1-590b00ee44b0.png)
The button can't be clicked!

**Comment by vyleung** [comment]
yes, local video support is planned. 

can you open dev tools (`ctrl+shift+i`) and see if there are any errors?

**Comment by mendax1234** [comment]
Sure, which part do you want to see?

**Comment by vyleung** [comment]
can you please do the following:
1. disable and re-enable the plugin
2. float the video and click the buttons
3. take a screenshot of the errors in the console and post it here

**Comment by mendax1234** [comment]
![image](https://user-images.githubusercontent.com/62934294/169736194-c176b878-22fc-4af6-91af-b62fb121d37c.png)

**Comment by mendax1234** [comment]
Every time l click the button to increase the height, it times of this error will be added.

**Comment by vyleung** [comment]
gotcha - could you send the video link so i can test it on my end?

**Comment by mendax1234** [comment]
Sure. https://www.youtube.com/watch?v=9s7zUlTgnDc&t=29s

**Comment by vyleung** [comment]
thanks, i’ll take a look in a bit

**Comment by vyleung** [comment]
it looks like the issue is that the video URL contains `&t=29s` - can you try `https://www.youtube.com/watch?v=9s7zUlTgnDc` instead?

**Comment by mendax1234** [comment]
Thanks , l will try it soon!

**Comment by mendax1234** [comment]
The problem is fixed! Thanks!
So, when will this function be added to the local video? Besides , can you also add this function to [bilibili](https://www.bilibili.com/)? Thank you very much!

**Comment by vyleung** [comment]
glad to hear that! 

can you open a new issue for local video support? and as far as i know, Logseq doesn't support bilibili embeds - other users have downloaded bilibili videos and embeded them as local videos so this will go hand-in-hand w/ the new issue

**Comment by mendax1234** [comment]
sure, thanks!
