### ISSUE TITLE
Change the size of the windows of local video

### ISSUE THREAD

**Issue by mendax1234** [vyleung/logseq-helium-plugin#7]
Hope this function can be added!

**Comment by vyleung** [comment]
added in v.2.0.0! 

disclaimer: a limitation is that the height and width of local videos can't exceed their original size - in other words, they can only get smaller, not larger

**Comment by mendax1234** [comment]
Thanks! l still can't change the size of the local video.

**Comment by vyleung** [comment]
closing this issue based on our discussion in #8
