### ISSUE TITLE
Change the size of Youtube video

### ISSUE THREAD

**Issue by mendax1234** [vyleung/logseq-helium-plugin#8]
l use Logseq 0.7.0 now and l find that l can't change the size of Youtube video.
Here is the youtube video link:https://www.youtube.com/watch?v=6Af6b_wyiwI
Here is my code to use it in the Logseq`{{video https://www.youtube.com/watch?v=6Af6b_wyiwI}}`
l hope the plugin can be updated to suit the latest version of Logseq. Thanks!

Daniel

**Comment by vyleung** [comment]
hi Daniel, i’m actively working on supporting the new `{{video }}` macro 🙂

**Comment by vyleung** [comment]
added in v.2.0.0! let me know if you run into any issues

**Comment by mendax1234** [comment]
Thanks! It works for youtube video now, but it doesn't work for the local video, even the start float function is not compatiable with the local video. Can you fix this? Thanks!

**Comment by vyleung** [comment]
can you share your local video syntax? the one i currently have supported is `![](local video path)`

**Comment by mendax1234** [comment]
[:video {:controls true :src "path"}]

**Comment by vyleung** [comment]
gotcha, i haven't seen this syntax before - i'll work on supporting it

**Comment by mendax1234** [comment]
Thanks, how can l use your syntax, since mine is from the logseq directly? If l wan to use your syntax by using "/..."how can l do that ? Can you have a look at it ,thanks!

**Comment by mendax1234** [comment]
l have tried your syntax and the video still can't be shown.

**Comment by vyleung** [comment]
can you update to v.2.0.1 and try again using your original syntax?

**Comment by mendax1234** [comment]
Sure!

**Comment by mendax1234** [comment]
It seems that you haven't updated the 2.0.1 release. It is still 2.0.0 in both you Github release and in the marketplace. @vyleung

**Comment by vyleung** [comment]
oops - i pushed the commit, but forgot to create a release 😅 please check again

**Comment by mendax1234** [comment]
Thanks , it works now , but it seems that there is a bug with this button.
![image](https://user-images.githubusercontent.com/62934294/171838355-13efbe9e-dbe8-4925-8a18-948375f4e1dc.png)
After the first click on the local video, it seems that the status of the video is wrong .
For example , like below
![image](https://user-images.githubusercontent.com/62934294/171838630-2f25271a-3a89-4929-b28b-0c50bf45b881.png)
Hope this can be fixed!

**Comment by vyleung** [comment]
hopefully v.2.0.2 fixes this issue

**Comment by mendax1234** [comment]
ok :joy: l am trying it now.

**Comment by mendax1234** [comment]
Thanks , this bug is fixed now , but l think l have found a new one. If l play the video first and then `start floating`, it seems that the state of the button is not consistent again.
![image](https://user-images.githubusercontent.com/62934294/171846524-8b3a52b7-924b-4b53-964b-3e764f8cbf5a.png)
Hope this can be fixed!

**Comment by vyleung** [comment]
try v.2.0.3 - thanks for finding all these bugs btw!

**Comment by mendax1234** [comment]
It works perfectly now! Thanks for fixing all the bugs 😄. BTW, hope the translation function can be added soon!
